import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/component/NavBarComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Simple Quicks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen flex-col items-end justify-end gap-y-5 bg-black p-2 lg:p-20">
          <div className="w-full bg-white lg:w-2/3 ">
            <div className="overflow-y-auto">{children}</div>
          </div>

          <NavBar />
        </div>
      </body>
    </html>
  );
}
